baseURL = "https://ccchengff.github.io/"
languageCode = "en-us"
title = "Fangcheng Fu"
theme = "notrack"
newContentEditor = "nvim"
paginate = 4

[params]
  author = "Fangcheng Fu"
  siteHeading = "Fangcheng Fu" # defaults to author
  favicon = "img/icon.png" # Adds a small icon next to the page title in a tab
  showBlogLatest = false
  showTaxonomyLinks = false
